name: SB_TELEFONIA
description: >
  Telefony System of Synapse Brasil
category: System
maintainer: Development Team of Synapse Brasil <dev@synapsebrasil.com.br> 
license: Freepbx
projectURL: https://github.com/MatheusBinicheski/sb_telefonia_docker.git
